Resources:
  JobApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "applicationId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "nextReminder"
          AttributeType: "S"
        - AttributeName: "company"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "applicationId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "JobApplications"
      GlobalSecondaryIndexes:
        - IndexName: "StatusIndex"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
            - AttributeName: "status"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "NextReminderIndex"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
            - AttributeName: "nextReminder"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "CompanyIndex"
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
            - AttributeName: "company"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"